### ISSUE TITLE
Widget possible?

### ISSUE THREAD

**Issue by zoroya1** [MGAndroidProjects/WeatherWise-Releases#4]
I've read readme and looks like flutter has no feature of widget so are you coming with a workaround for widget or it's not possible? 
Btw app is great with best MY theme interface.
Just missing material you widget of weather wise

**Comment by milindgoel15** [comment]
It basically means that flutter does not provide any flutter side functionality to build widgets. I don't really think flutter will ever build something that will ease up the process of making widgets.

The only way to make widgets is through native side. Currently I don't have knowledge in XML layouts and how to connect with flutter but it is possible.

**Comment by milindgoel15** [comment]
Added with v2.1.0

**Comment by zoroya1** [comment]
Thank you so much 😊 looks so nice 🌟
Can we make the widget background transparent?

**Comment by milindgoel15** [comment]
> Can we make the widget background transparent?

In the next update, I am separating both widget sizes into separate widgets due to widget height issues on a few devices. So the small-sized widget will be a transparent one. But the normal regular-sized widget will continue to have a coloured background.


![Screenshot_1690904053](https://github.com/MGAndroidProjects/WeatherWise-Releases/assets/45682747/5387ab36-ef5c-4574-9b60-17201a1709fb)

**Comment by zoroya1** [comment]
![ResizedImage_2023-08-01_21-33-17_0.jpg](https://github.com/MGAndroidProjects/WeatherWise-Releases/assets/128675129/add75f58-d72e-4207-b1bc-5f6ac1942974)

Transparent background one can also look like this with material you colour in city name and other as we currently have

**Comment by milindgoel15** [comment]
I am not sure if everyone will like it.

**Comment by milindgoel15** [comment]
I could add a configuration activity which lets users customise the appearance. Maybe

**Comment by milindgoel15** [comment]
Closing this as I really don't feel I will add configuration activity for it. May do it in future. But at least there are widgets now.
