### ISSUE TITLE
Colour coded forecast

### ISSUE THREAD

**Issue by Kayetic** [MGAndroidProjects/WeatherWise-Releases#5]
Suggestion:

In the forecast tab, It would be useful to differentiate the different days if the same day could be lightly shaded with an accent colour, then the next day's couple of temperatures to have a slightly different colour and so on.

Tldr:
- In forecast tab
- Colour code each day's couple of temperatures.
- Different colours for the different shades.

![Screenshot_20230619-124044](https://github.com/MGAndroidProjects/WeatherWise-Releases/assets/99417935/12965fde-a7bf-4d13-bc14-03b059ae27ea)

**Comment by milindgoel15** [comment]
So you mean, each day in the forecast could use a different background
19: A color
20: B color
21: C color
so on

**Comment by milindgoel15** [comment]
Not sure if it will look good. We can render one color for today and a different color for other days:
![image](https://github.com/MGAndroidProjects/WeatherWise-Releases/assets/45682747/b0cd4e0e-e208-4291-9941-621dbe7df534)

**Comment by Kayetic** [comment]
That would probably work yes, and from the preview, yes probably doesn't look good but if we were to make it only a **slightly different shade** (maybe using the accent colour from monet) from the normal dark/light colour

For example:
[https://www.figma.com/community/file/1252967060450216410](https://www.figma.com/community/file/1252967060450216410)

<img width="382" alt="image" src="https://github.com/MGAndroidProjects/WeatherWise-Releases/assets/99417935/48960b4e-a1c8-4dd6-99e3-084dcde63669">

<img width="379" alt="image" src="https://github.com/MGAndroidProjects/WeatherWise-Releases/assets/99417935/bfac7ea2-6db8-4012-8f0e-3a03485c4947">

Light Colour used: #E8F3DD
Dark Colour used: #232720


In this example, the change in colour is **very slight**, and is more pronounced in the light theme but that can be adjusted according to which theme is used.

**Comment by milindgoel15** [comment]
Just as the example yea:

<img src="https://github.com/MGAndroidProjects/WeatherWise-Releases/assets/45682747/b13dad60-f7dc-4c82-bbcd-07503687558b" width="382" alt="light">
<img src="https://github.com/MGAndroidProjects/WeatherWise-Releases/assets/45682747/318afcad-bbb5-42c4-9f77-b4a0f8d6ab4a" width="382" alt="dark">

**Comment by Kayetic** [comment]
Yes, definitely something along those lines, maybe even a little less emphasised or saturated.

**Comment by milindgoel15** [comment]
I can't control the colors as they are dynamically chosen by the material you engine on Android devices. These colors are not defined by me. 

https://m3.material.io/styles/color/overview

**Comment by Kayetic** [comment]
There was something mentioned in the docs about 'additional accent colors'
![Screenshot_20230621-120300](https://github.com/MGAndroidProjects/WeatherWise-Releases/assets/99417935/663dd6ac-9adb-40e2-abf6-91fc2fcd7e37)

Or about One color becoming 13 or more:

![Screenshot_20230621-120353](https://github.com/MGAndroidProjects/WeatherWise-Releases/assets/99417935/d6fc6221-d1d8-44d8-a9a2-7846cf4aba7c)


But obviously, this is **your project**, and if it cannot be done, it was just a suggestion I had, the app is amazing by itself anyway :))

**Comment by milindgoel15** [comment]
Dont, think the dynamic color library provides a way to specify what tone we want. It only provides the default accent and neutral values. The additional colors are just the error and static color we can provide but providing static may or may not suit every background and accent.

**Comment by Kayetic** [comment]
I saw that you included this feature in the app now. Thank you!
