### ISSUE TITLE
Different forecast icons

### ISSUE THREAD

**Issue by HotarunIchijou** [MGAndroidProjects/WeatherWise-Releases#6]
![](https://github.com/MGAndroidProjects/WeatherWise-Releases/assets/113282550/7ece63f3-c36f-4334-91cb-484f28dd55d9)
![](https://github.com/MGAndroidProjects/WeatherWise-Releases/assets/113282550/fae16100-adfc-412d-b36e-b747ce7aaa21)

**Comment by milindgoel15** [comment]
![image](https://github.com/MGAndroidProjects/WeatherWise-Releases/assets/45682747/f9ff62cf-3809-490e-a5c9-8889c716be17)
better yea?

**Comment by HotarunIchijou** [comment]
Maybe just cloud would be better?

**Comment by milindgoel15** [comment]
> Maybe just cloud would be better?

Icon we already had was already the cloud icon. (The one shown in your provided screenshot)

> ![image](https://user-images.githubusercontent.com/45682747/249222057-f9ff62cf-3809-490e-a5c9-8889c716be17.png) better yea?

I think this matches out the inactive tab icon perfectly

**Comment by HotarunIchijou** [comment]
I mean, wouldn't be better if icon just be a cloud, not cloud in a circle? (Flutter ID for inactive: cloud_outlined, Flutter ID for active: cloud)

**Comment by milindgoel15** [comment]
oh you meant the inactive icon needed the change. Will use the cloud_outlined one now.

**Comment by milindgoel15** [comment]
Added with 2.0.0
