### ISSUE TITLE
Add to F-Droid

### ISSUE THREAD

**Issue by fillwithjoy1** [MGAndroidProjects/WeatherWise-Releases#7]
**Is your feature request related to a problem? Please describe.**
This app is seriously amazing, and I think more people should see it

**Describe the solution you'd like**
Add this to F-Droid

**Describe alternatives you've considered**
There's IzzyDroid, uhh can't remember others

**Additional context**
Nothing else

**Comment by fillwithjoy1** [comment]
just realized this is closed source

**Comment by milindgoel15** [comment]
Fdroid requires apps to be open source so this is not possible.
