### ISSUE TITLE
Android 14 support 

### ISSUE THREAD

**Issue by HotarunIchijou** [MGAndroidProjects/WeatherWise-Releases#8]
Unable to install the app on the latest Android 14 QPR beta, package installer just crashes

**Comment by milindgoel15** [comment]
Please try again on Android 14 stable releases.

**Comment by HotarunIchijou** [comment]
Still can't install on QPR. It works on stable version, but not on the QPR

**Comment by milindgoel15** [comment]
Try 2.3.4 release. I wouldn't recommend using QPR builds as a daily driver.

**Comment by HotarunIchijou** [comment]
Yeah, I tried that, not working. I prefer to use QPR because even stable version for my device is extremely buggy, so I would to know if the issues were resolved in the new build, and if not, report that to the issue tracker

**Comment by HotarunIchijou** [comment]
Lol, I've installed the app with SAI. Thanks, I'll use this as a temporary solution, so it should be a bug with android package instsller, which I already reported to the Google issue tracker
