### ISSUE TITLE
App Can't be installed on windows due to error 0x800B010A

### ISSUE THREAD

**Issue by darkpurpleof** [MGAndroidProjects/WeatherWise-Releases#9]
**Describe the bug**
Certificate is invalid on package installer on Windows 11 x64 devices

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Download Windows Installer in .msix'
2. Click on 'Open/Install'
3. Install Button Grayed out
4. See the error

**Expected behaviour**
Install Weatherwise as expected 

**Screenshots**
![Captura de pantalla 2024-04-29 183238](https://github.com/MGAndroidProjects/WeatherWise-Releases/assets/113225306/884af72f-56e9-4c0a-ab11-d1dcb2d84629)

**Desktop (please complete the following information):**
 - Device: [Intel Board]
 - OS: [Windows 11 x64]
 - Version [2.3.7.0]

**Additional context**
Installer says about an invalid certificate in the app's structure and that it can't be installed because of it (Invalid Developer Certificate)

**Comment by milindgoel15** [comment]
https://www.youtube.com/watch?v=QKhr7a783wA


Check out this guide to install certificate manually
